FROM node:18-alpine
ENV NODE_ENV development

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
COPY package.json .

#RUN npm install
RUN npm install

# Copy app files
COPY . .

# Expose port
EXPOSE 8080

# Start the app
CMD [ "npm", "run", "dev" ]