version: "3.8"

services:
  frontend:
    container_name: gg-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
  backend:
    container_name: gg-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "5001:8080"
    depends_on:
      - database
  database:
    container_name: gg-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongPassword123
    volumes:
      - db-data-test:/var/opt/mssql
  database-migration:
    container_name: gg-database-migration
    build:
      context: ./backend
      dockerfile: Dockerfile.migration
    ports:
      - "5001:8080"
    volumes:
      - type: bind
        source: ./backend/Migrations
        target: /app/Migrations
    # interactive container
    stdin_open: true
    tty: true
    #environment:
    #  - NAME=DefaultMigrationName
    depends_on:
      - database
    profiles:
      - database-migration
volumes:
  db-data-test:
