version: "3.8"
services:
  backend:
    container_name: gg-backend
    build: /backend
    ports: 
      - '5001:8080'
    depends_on:
      - database
  database:
    container_name: gg-database 
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongPassword123
