version: "3.8"

services:
  frontend:
    container_name: dev-gg-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
    ports:
      - "8080:8080"
  backend:
    container_name: dev-gg-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:8080"
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./backend
        target: /app
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: .
  database:
    container_name: dev-gg-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongPassword123
